title: yokai.wiki
description: The Yo-Kai Watch documentation site.
remote_theme: just-the-docs/just-the-docs

color_scheme: dark

url: "https://ykw-modding.github.io/yo-docs"

aux_links:
  The Yo-kai Watch Modding Discord: https://discord.gg/TbmKf6Ujq3
  The Yo-kai Watch Speedrunning Discord: https://discord.gg/eZsQ9Zts7d

just_the_docs:
  custom_css:
    - assets/css/custom.css

aux_links_new_tab: true

nav_sort: case_sensitive
#theme: "just-the-docs"
